# Generated by Django 5.2.16 on 2026-08-02 07:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresponse',
            name='video_file',
            field=models.FileField(blank=True, help_text='Recorded webcam video clip for this answer', null=True, upload_to=core.models.interview_video_path),
        ),
    ]
