# Generated by Django 5.2.16 on 2026-08-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_interviewevaluation_ai_analysis_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewevaluation',
            name='ai_analysis_summary',
        ),
        migrations.RemoveField(
            model_name='interviewevaluation',
            name='emotion_score_avg',
        ),
        migrations.RemoveField(
            model_name='interviewevaluation',
            name='integrity_score_avg',
        ),
        migrations.RemoveField(
            model_name='interviewevaluation',
            name='total_violations',
        ),
        migrations.RemoveField(
            model_name='interviewevaluation',
            name='voice_confidence_avg',
        ),
        migrations.RemoveField(
            model_name='interviewresponse',
            name='proctoring_data',
        ),
        migrations.AlterField(
            model_name='interviewevaluation',
            name='recommendation',
            field=models.CharField(choices=[('recommended', 'Recommended'), ('not_recommended', 'Not Recommended')], default='not_recommended', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewresponse',
            name='emotion_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='interviewresponse',
            name='voice_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
